name: Build and Deploy to /docs

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit Message'
        required: false
        default: 'build and deploy actions workflow'
  push:
    branches: [ master ]

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]')
    permissions:
      contents: write

    runs-on: ubuntu-latest

    env:
      GitHub: true
      COMMIT_MESSAGE: ${{ github.event.inputs.commit_message || 'build and deploy actions workflow' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'

    - name: Install dependencies
      run: npm install --verbose

    - name: Run build
      run: npm run build --verbose

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: docs
        target-folder: docs
        commit-message: ${{ env.COMMIT_MESSAGE }}
        clean: true